### ISSUE TITLE
Adding a tooltip to reaction

### ISSUE THREAD

**Issue by eman1986** [AmrDeveloper/ReactButton#8]
I like this library, one small thing I'd like is a tooltip like facebook has on their dialog.

**Comment by AmrDeveloper** [comment]
Hello @eman1986 Thanks for your feedback and i will add this feature in the TODO list and implement it soon with a lot of customization, once i finish and release i will mention you in this issue

Thanks
Amr Hesham

**Comment by AmrDeveloper** [comment]
Hello @eman1986 Tooltip feature is released in version 2.0.3 with customization options, change color, shape, text

![facebook_reacts_portal](https://user-images.githubusercontent.com/23631699/136447610-ea6140be-0a96-4a44-a374-ae8abaed3294.png)

Enjoy ReactButton 👍🏻 

Thanks
Amr Hesham

**Comment by eman1986** [comment]
That's awesome, thanks for the quick response.
